import type {
  Application,
  CandidateProfile,
  Dispute,
  Job,
  Notification,
  RecruiterProfile,
  Stake,
} from "@/lib/types";
import { StakeStatus, StakeType } from "@/lib/types";

// Fixed base time so server and client renders agree (no Date.now drift).
export const NOW = Date.parse("2026-06-11T09:00:00Z");
const DAY = 86400000;

export type SeedRecruiter = RecruiterProfile & { id: string; wallet: string };
export type SeedTalent = CandidateProfile & { id: string; wallet: string };

export const recruiters: SeedRecruiter[] = [
  {
    id: "rec_aperture",
    wallet: "0xA1b2C3d4E5f6A7b8C9d0E1f2A3b4C5d6E7f80001",
    companyName: "Aperture Labs",
    companyWebsite: "https://aperture.xyz",
    companyDescription: "Onchain identity tooling for the Celo ecosystem.",
    contactEmail: "talent@aperture.xyz",
    location: "Remote · GMT+1",
    verificationStatus: "VERIFIED",
    trustLevel: 88,
    completedHires: 12,
    disputeCount: 0,
  },
  {
    id: "rec_mesh",
    wallet: "0xA1b2C3d4E5f6A7b8C9d0E1f2A3b4C5d6E7f80002",
    companyName: "Mesh Protocol",
    companyWebsite: "https://mesh.fi",
    companyDescription: "Cross-chain liquidity routing.",
    contactEmail: "jobs@mesh.fi",
    location: "Remote · Global",
    verificationStatus: "VERIFIED",
    trustLevel: 81,
    completedHires: 6,
    disputeCount: 0,
  },
  {
    id: "rec_northwind",
    wallet: "0xA1b2C3d4E5f6A7b8C9d0E1f2A3b4C5d6E7f80003",
    companyName: "Northwind",
    companyWebsite: "https://northwind.design",
    companyDescription: "Product design studio for early-stage teams.",
    location: "Lisbon · GMT",
    verificationStatus: "PENDING",
    trustLevel: 64,
    completedHires: 2,
    disputeCount: 0,
  },
  {
    id: "rec_brightside",
    wallet: "0xA1b2C3d4E5f6A7b8C9d0E1f2A3b4C5d6E7f80004",
    companyName: "Brightside Analytics",
    companyDescription: "Growth and data for consumer apps.",
    location: "Remote · GMT-5",
    verificationStatus: "UNVERIFIED",
    trustLevel: 41,
    completedHires: 0,
    disputeCount: 0,
  },
  {
    id: "rec_quickcoin",
    wallet: "0xA1b2C3d4E5f6A7b8C9d0E1f2A3b4C5d6E7f80005",
    companyName: "QuickCoin Rewards",
    companyDescription: "Earn crypto fast.",
    location: "Unknown",
    verificationStatus: "UNVERIFIED",
    trustLevel: 12,
    completedHires: 0,
    disputeCount: 2,
  },
];

export const jobs: Job[] = [
  {
    id: "job_fe_aperture",
    recruiterId: "rec_aperture",
    title: "Senior Frontend Engineer",
    description:
      "We're hiring a senior frontend engineer to lead our Celo Mini App experience. You'll own the React + TypeScript codebase, build wallet-native flows, and partner with design on a mobile-first product used by thousands of candidates. Comfortable with viem/wagmi and design systems.",
    companyName: "Aperture Labs",
    location: "Remote",
    remote: true,
    salaryRange: "$90k – $130k",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skillsRequired: ["React", "TypeScript", "Tailwind", "viem", "Design systems"],
    status: "ACTIVE",
    stakeAmount: 5,
    stakeToken: "cUSD",
    stakeStatus: StakeStatus.Locked,
    candidateStakeRequired: false,
    riskLevel: "LOW",
    riskScore: 12,
    createdAt: NOW - 4 * DAY,
    expiresAt: NOW + 24 * DAY,
  },
  {
    id: "job_sol_mesh",
    recruiterId: "rec_mesh",
    title: "Solidity Engineer",
    description:
      "Mesh Protocol is looking for a Solidity engineer to design and ship upgradeable contracts. You'll write Foundry tests, work with OpenZeppelin upgradeable patterns, and collaborate on audits. Strong fundamentals in security and gas optimization required.",
    companyName: "Mesh Protocol",
    location: "Remote",
    remote: true,
    salaryRange: "$120k – $170k",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skillsRequired: ["Solidity", "Foundry", "OpenZeppelin", "Security"],
    status: "ACTIVE",
    stakeAmount: 8,
    stakeToken: "cUSD",
    stakeStatus: StakeStatus.Locked,
    candidateStakeRequired: true,
    candidateStakeAmount: 2,
    riskLevel: "LOW",
    riskScore: 18,
    createdAt: NOW - 6 * DAY,
    expiresAt: NOW + 18 * DAY,
  },
  {
    id: "job_design_northwind",
    recruiterId: "rec_northwind",
    title: "Product Designer",
    description:
      "Northwind is hiring a product designer to shape early-stage Web3 products end to end — from research to high-fidelity prototypes. You'll work directly with founders and engineers in a tight feedback loop.",
    companyName: "Northwind",
    location: "Lisbon / Remote",
    remote: true,
    salaryRange: "$70k – $95k",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    skillsRequired: ["Figma", "Prototyping", "Design systems", "User research"],
    status: "ACTIVE",
    stakeAmount: 12,
    stakeToken: "cUSD",
    stakeStatus: StakeStatus.Locked,
    candidateStakeRequired: false,
    riskLevel: "MEDIUM",
    riskScore: 44,
    createdAt: NOW - 2 * DAY,
    expiresAt: NOW + 26 * DAY,
  },
  {
    id: "job_data_brightside",
    recruiterId: "rec_brightside",
    title: "Data Analyst",
    description:
      "Looking for a data analyst to own dashboards and growth reporting. SQL and a BI tool required.",
    companyName: "Brightside Analytics",
    location: "Remote",
    remote: true,
    salaryRange: "Negotiable",
    jobType: "CONTRACT",
    experienceLevel: "MID",
    skillsRequired: ["SQL", "Dashboards", "Analytics"],
    status: "ACTIVE",
    stakeAmount: 15,
    stakeToken: "cUSD",
    stakeStatus: StakeStatus.Locked,
    candidateStakeRequired: false,
    riskLevel: "MEDIUM",
    riskScore: 52,
    createdAt: NOW - 1 * DAY,
    expiresAt: NOW + 12 * DAY,
  },
  {
    id: "job_cm_quickcoin",
    recruiterId: "rec_quickcoin",
    title: "Community Manager — Earn Fast",
    description:
      "Urgent hire! Earn guaranteed income working from home. Small registration fee required to start. Contact us on Telegram to begin onboarding today.",
    companyName: "QuickCoin Rewards",
    location: "Remote",
    remote: true,
    salaryRange: "$8,000/mo guaranteed",
    jobType: "PART_TIME",
    experienceLevel: "JUNIOR",
    skillsRequired: ["Discord", "Telegram"],
    status: "FLAGGED",
    stakeAmount: 2,
    stakeToken: "cUSD",
    stakeStatus: StakeStatus.Locked,
    candidateStakeRequired: false,
    riskLevel: "HIGH",
    riskScore: 86,
    createdAt: NOW - 12 * 3600000,
    expiresAt: NOW + 6 * DAY,
  },
  {
    id: "job_devops_aperture",
    recruiterId: "rec_aperture",
    title: "DevOps Engineer",
    description:
      "Own our CI/CD, infra-as-code, and observability stack across staging and production. Experience with Docker, Terraform, and monitoring tooling expected. You'll keep deploys boring and reliable.",
    companyName: "Aperture Labs",
    location: "Remote",
    remote: true,
    salaryRange: "$100k – $140k",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skillsRequired: ["Docker", "Terraform", "CI/CD", "Monitoring"],
    status: "CLOSED",
    stakeAmount: 5,
    stakeToken: "cUSD",
    stakeStatus: StakeStatus.Refunded,
    candidateStakeRequired: false,
    riskLevel: "LOW",
    riskScore: 14,
    createdAt: NOW - 40 * DAY,
    expiresAt: NOW - 4 * DAY,
  },
];

export const talents: SeedTalent[] = [
  {
    id: "tal_sara",
    wallet: "0xC0ffee254729296a45a3885639AC7E10F9d54979",
    displayName: "Sara Lindgren",
    bio: "Frontend engineer who loves wallet-native UX and design systems.",
    skills: ["React", "TypeScript", "Tailwind", "viem", "Figma"],
    roleTargets: ["Frontend Engineer", "Design Engineer"],
    experienceLevel: "SENIOR",
    portfolioUrl: "https://sara.dev",
    githubUrl: "https://github.com/sara",
    location: "Berlin",
    timezone: "GMT+1",
    languages: ["English", "German"],
    salaryExpectation: "$110k",
    visibility: "PUBLIC",
  },
  {
    id: "tal_daniel",
    wallet: "0xD4n1e10729296a45a3885639AC7E10F9d540002",
    displayName: "Daniel Okafor",
    bio: "Smart-contract engineer focused on security and upgradeable patterns.",
    skills: ["Solidity", "Foundry", "OpenZeppelin", "Security"],
    roleTargets: ["Solidity Engineer", "Protocol Engineer"],
    experienceLevel: "SENIOR",
    githubUrl: "https://github.com/danielo",
    location: "Lagos",
    timezone: "GMT+1",
    languages: ["English"],
    salaryExpectation: "$150k",
    visibility: "PUBLIC",
  },
  {
    id: "tal_priya",
    wallet: "0xP91ya0729296a45a3885639AC7E10F9d5400003",
    displayName: "Priya Nair",
    bio: "Product designer turning fuzzy problems into shippable flows.",
    skills: ["Figma", "Prototyping", "User research", "Design systems"],
    roleTargets: ["Product Designer"],
    experienceLevel: "MID",
    portfolioUrl: "https://priya.design",
    location: "Bangalore",
    timezone: "GMT+5:30",
    languages: ["English", "Hindi"],
    salaryExpectation: "$85k",
    visibility: "PUBLIC",
  },
  {
    id: "tal_marco",
    wallet: "0xM4rc00729296a45a3885639AC7E10F9d5400004",
    displayName: "Marco Bianchi",
    bio: "Full-stack dev moving into Web3, strong on data and dashboards.",
    skills: ["SQL", "TypeScript", "Dashboards", "Analytics"],
    roleTargets: ["Data Analyst", "Full-stack Engineer"],
    experienceLevel: "JUNIOR",
    githubUrl: "https://github.com/marcob",
    location: "Milan",
    timezone: "GMT+1",
    languages: ["English", "Italian"],
    salaryExpectation: "$70k",
    visibility: "PUBLIC",
  },
];

export const seedApplications: Application[] = [
  {
    id: "app_sara_fe",
    jobId: "job_fe_aperture",
    candidateId: "tal_sara",
    status: "INTERVIEW",
    message: "Led a wallet-native rewrite at my last role — would love to do it here.",
    matchScore: 92,
    riskScore: 12,
    appliedAt: NOW - 3 * DAY,
    updatedAt: NOW - 1 * DAY,
  },
  {
    id: "app_daniel_sol",
    jobId: "job_sol_mesh",
    candidateId: "tal_daniel",
    status: "OFFERED",
    message: "Shipped two audited upgradeable systems. Staked and serious.",
    matchScore: 95,
    riskScore: 18,
    stakeId: "stk_daniel_app",
    appliedAt: NOW - 5 * DAY,
    updatedAt: NOW - 6 * 3600000,
  },
  {
    id: "app_priya_design",
    jobId: "job_design_northwind",
    candidateId: "tal_priya",
    status: "REVIEWED",
    message: "Portfolio attached — happy to do a paid trial task.",
    matchScore: 88,
    riskScore: 44,
    appliedAt: NOW - 1 * DAY,
    updatedAt: NOW - 12 * 3600000,
  },
  {
    id: "app_marco_data",
    jobId: "job_data_brightside",
    candidateId: "tal_marco",
    status: "APPLIED",
    message: "Strong SQL, building out my BI portfolio.",
    matchScore: 71,
    riskScore: 52,
    appliedAt: NOW - 8 * 3600000,
    updatedAt: NOW - 8 * 3600000,
  },
];

export const seedStakes: Stake[] = [
  {
    id: "stk_fe_post",
    userId: "rec_aperture",
    jobId: "job_fe_aperture",
    stakeType: StakeType.JobPost,
    amount: 5,
    token: "cUSD",
    status: StakeStatus.Locked,
    txHash: "0xb1a7c0de00000000000000000000000000000000000000000000000000000001",
    createdAt: NOW - 4 * DAY,
    updatedAt: NOW - 4 * DAY,
  },
  {
    id: "stk_sol_post",
    userId: "rec_mesh",
    jobId: "job_sol_mesh",
    stakeType: StakeType.JobPost,
    amount: 8,
    token: "cUSD",
    status: StakeStatus.Locked,
    txHash: "0xb1a7c0de00000000000000000000000000000000000000000000000000000002",
    createdAt: NOW - 6 * DAY,
    updatedAt: NOW - 6 * DAY,
  },
  {
    id: "stk_daniel_app",
    userId: "tal_daniel",
    jobId: "job_sol_mesh",
    applicationId: "app_daniel_sol",
    stakeType: StakeType.Application,
    amount: 2,
    token: "cUSD",
    status: StakeStatus.Locked,
    txHash: "0xb1a7c0de00000000000000000000000000000000000000000000000000000003",
    createdAt: NOW - 5 * DAY,
    updatedAt: NOW - 5 * DAY,
  },
  {
    id: "stk_devops_post",
    userId: "rec_aperture",
    jobId: "job_devops_aperture",
    stakeType: StakeType.JobPost,
    amount: 5,
    token: "cUSD",
    status: StakeStatus.Refunded,
    txHash: "0xb1a7c0de00000000000000000000000000000000000000000000000000000004",
    createdAt: NOW - 40 * DAY,
    updatedAt: NOW - 4 * DAY,
  },
  {
    id: "stk_quickcoin_post",
    userId: "rec_quickcoin",
    jobId: "job_cm_quickcoin",
    stakeType: StakeType.JobPost,
    amount: 2,
    token: "cUSD",
    status: StakeStatus.Locked,
    txHash: "0xb1a7c0de00000000000000000000000000000000000000000000000000000005",
    createdAt: NOW - 12 * 3600000,
    updatedAt: NOW - 12 * 3600000,
  },
];

export const seedDisputes: Dispute[] = [
  {
    id: "dsp_quickcoin",
    reporterId: "tal_marco",
    reportedLabel: "QuickCoin Rewards",
    jobId: "job_cm_quickcoin",
    stakeId: "stk_quickcoin_post",
    reason: "Job asked for a registration fee and pushed to Telegram off-platform.",
    status: "UNDER_REVIEW",
    aiSummary:
      "Reporter flagged an upfront fee and off-platform contact. Listing shows multiple scam signals (fee, urgency, off-platform). Recommend slashing the post stake and suspending the recruiter pending response.",
    createdAt: NOW - 6 * 3600000,
  },
];

export const seedNotifications: Notification[] = [
  { id: "n1", text: "Mesh Protocol moved your application to Offered", time: "6m", unread: true },
  { id: "n2", text: "Aperture Labs scheduled an interview", time: "1h", unread: true },
  { id: "n3", text: "Your job-post stake of 5 cUSD is locked", time: "4h", unread: false },
];
