process.env.OPENROUTER_API_KEY ??= "test-openrouter-api-key";
process.env.TOKENROUTER_API_KEY ??= "test-tokenrouter-api-key";

await Promise.all([
  import("./agent-runner.test"),
  import("./chat-thread.test"),
  import("./env.test"),
  import("./embeddings.test"),
  import("./cv-normalizer.test"),
  import("./guardrails.test"),
  import("./chat-agent.test"),
  import("./chat-guard.test"),
  import("./chat-request-logging.test"),
  import("./jobs-data.test"),
  import("./knowledge.test"),
  import("./memory.test"),
  import("./model-router.test"),
  import("./package-scripts.test"),
  import("./parse-cv-pipeline.test"),
  import("./product-knowledge.test"),
  import("./runtime.test"),
  import("./server.test"),
  import("./tools.test"),
  import("./usage.test"),
  import("./workflows.test"),
  import("./chat-validation.test"),
  import("./rate-limit.test"),
  import("./chat-caller.test"),
  import("./security-indicators.test"),
  import("./output-validation.test"),
  import("./chat-output-processor.test"),
  import("./security-guard.test"),
  import("./security-policy.test"),
  import("./job-contracts.test"),
  import("./in-memory-job-queue.test"),
  import("./job-processors.test"),
  import("./cv-agent-generator.test"),
  import("./cv-parse-processor.test"),
  import("./cv-document.test"),
  import("./agent-worker.test"),
  import("./jobs-http.test"),
  import("./live-cv-worker.test"),
]);
